### ISSUE TITLE
Legal part of keeping authorization key for undocumented API

### ISSUE THREAD

**Issue by invidian** [leuchte/number26#1]
It's only partially connected with this repository, although it's always good to ask. I decided to create an issue instead of writing email, because those information might be useful for other people.

I'm thinking about writing ruby bindings for Number26 API, and I was wondering if it's legal to keep `authorization key` (which is required to get personal token) inside own library.

DId you ask Number26 about that?

**Comment by leuchte** [comment]
What do you mean with `authorization key`? The `authorization_token` you receive after each login? Or the e-mail/password combo, you need to login?

It doesn't make much sense to keep the `authorization_token`, since after 30 minutes you have to request a new one. I think, to store e-mail and password is not allowed in terms of service.

Anyway, i asked nobody.

**Comment by invidian** [comment]
Sorry, that I didn't mention that, I was talking about [this basic authorization](https://github.com/leuchte/number26/blob/master/src/Number26.php#L174), which is used to get personalized token. BTW, it comes from [there](https://my.number26.de/js/models/users/LoginModel_.js?build=2.1.17) and that would be better idea to download it from there instead of hardcoding it.

**Comment by leuchte** [comment]
Oh, that. Well its a base64 encoded string of a allowed client that can access the API. There is just the used one, one for android devices and maybe one for iOS. So, i don't see the need to not hardcode it since you can't register or activate your own client.

**Comment by invidian** [comment]
Yeah, I just started reading about `spring oauth2`, which they use and I figured it out by myself. Anyway, thanks for answers! I think it can be closed.
