### ISSUE TITLE
Bad Request Exception for query

### ISSUE THREAD

**Issue by pscheit** [leuchte/number26#11]
/app/vendor/leuchte/number26/src/Number26.php:111

Stopped working yesterday, did they change something?

Thanks for developing this

Best regards
Philipp

**Comment by leuchte** [comment]
Seems like they did. I think we have to wait. Maybe there is no happy end this time

**Comment by pscheit** [comment]
yes :( i followed the thread for python n26 as well.. this looks bad.

I was already wondering if there is a PSD2 licensed service that will open it's own api so that we could use it?

damn.. the csv export is missing the transaction id ...

**Comment by leuchte** [comment]
So, there is a new required header-tag "device-token". There are two possible solutions to hand over a device token. Either hardcoded , maybe as a config variable. Or we generate one on the run. Thats what i have decided. Before running the first API call, the device token is set automatically. Hopefully they change nothing else in the future, but i doubt it.

**Comment by pscheit** [comment]
awesome. Thank you!
