### ISSUE TITLE
Login not working anymore /oauth/token

### ISSUE THREAD

**Issue by lanort** [leuchte/number26#12]
It looks like N26 changed its structure again, as I can't download the transactions anymore.

I used the example from the start page:

    <?php
    $n26 = new leuchte\Number26\Number26('email@example.com', 'mypassword');

    // Get transactions
    $transactions = $n26->getTransactions(['sort' => 'visibleTS', 'dir' => 'ASC', 'offset' => 0, 'limit' => 200]);

It looks like getting the oauth token fails, as the API result for that is a "HTTP/1.1 401 Unauthorized".

Maybe this is an alternative
https://n26.dashboard.sandbox.token.io/swagger

**Comment by leuchte** [comment]
Latest update should fix this. Atleast for now.

> Maybe this is an alternative
> https://n26.dashboard.sandbox.token.io/swagger

Feb 3, 2021 token.io interface (deprecated from Nov 4, 2020) will be fully disabled from Mar 1st, 2021
[https://support.n26.com/en-eu/security/opening-banking-psd2/psd2-open-banking-for-third-party-providers](url)

**Comment by leuchte** [comment]
Latest update should fix this. Atleast for now.

> Maybe this is an alternative
> https://n26.dashboard.sandbox.token.io/swagger

> **Feb 3, 2021 token.io interface (deprecated from Nov 4, 2020) will be fully disabled from Mar 1st, 2021**

[https://support.n26.com/en-eu/security/opening-banking-psd2/psd2-open-banking-for-third-party-providers](url)
