### ISSUE TITLE
invalid_token but isValidConnection() still returns true.

### ISSUE THREAD

**Issue by zNoobs** [leuchte/number26#3]
Hi,
Sometimes the token becomes invalid but the cookie session is still here so your method isValidConnection() still returns true.
You should check in callApi if the apiResponse returns an error I think:
if(isset($this->apiResponse->error) AND  $this->apiResponse->error == "invalid_token"){
			//do something because session is not valid anymore
		}

Best regards.

**Comment by leuchte** [comment]
Yes, you are right. But i think this just happens, when you use the API and the website at the same time, no? Anyway, thank you very much for your report.

**Comment by zNoobs** [comment]
I was not connected to the website, but my connection is changing IP really
often so it might be this.
By the way sometimes I'm not getting any result when I try to get
transactions.
It might be my connection too, I'm in Thailand.
Thanks for you API it's usefull and can get more details than the original
websites!

On Jan 9, 2018 18:02, "André" <notifications@github.com> wrote:

Yes, you are right. But i think this just happens, when you use the API and
the website at the same time, no? Anyway, thank you very much for your
report.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/leuchte/number26/issues/3#issuecomment-356252486>, or mute
the thread
