### ISSUE TITLE
Transfer not working anymore?

### ISSUE THREAD

**Issue by Luuk2016** [leuchte/number26#5]
Im trying to do a transfer, however the transfer doesn't succeed.
My credentials are ok because i can see my transactions.
If i var_dump the makeTransfer function i get this response:
![afbeelding](https://user-images.githubusercontent.com/24903547/57774644-5a0af280-771b-11e9-8812-f5224423c002.png)
Are you sure the endpoint is still up-to-date?

**Comment by leuchte** [comment]
The reason the server responded with this message, is the missing accept header (removed in https://github.com/leuchte/number26/commit/d114fa219ec924ed7f2e7ea2b5300e58b9f44e19). However, it seems that N26 removed the sendTransaction endpoint and with this API it is not possible to send transactions anymore.

Maybe i've got time to look into the new GraphQL-API, but i can't promise anything.

Thank you for your message.
