### ISSUE TITLE
mfa_required: MFA token is required

### ISSUE THREAD

**Issue by nevets963** [leuchte/number26#6]
When I call the N26 API now, I get the error: mfa_required: MFA token is required from their API.

I noticed that when a API error is called, 'die' is called. I suggest we change this to throw an exception instead. But, would you know a workaround for this? I guess MFA is multi-factor authentication...

**Comment by zNoobs** [comment]
The message returned by N26 API is:
`{"userMessage":{"title":"A second authentication factor is required.","detail":"Please provide your second form of authentication."},"mfaToken":"xxxxxx-your-mfaToken-token-xxxxx","error_description":"MFA token is required","detail":"MFA token is required","hostUrl":"https://api.tech26.de","type":"mfa_required","error":"mfa_required","title":"A second authentication factor is required.","message":"Please provide your second form of authentication.","userId":"xxxxxx-your-user-id-xxxxx","status":403}`

The solution is to delete the cookies, you can use the "logout()" function to do this, and login again.

**Comment by zNoobs** [comment]
My bad, now N26 asks for 2FA all the time, before I could avoid by deleting the cookie, now can't...
The message when you login (to the web app):

> Two-Factor Authentication helps to prevent others from gaining fraudulent access to your account.
> 
> For added security, you'll always be asked to verify your sign in on your phone each time you login from a new browser or device. All it takes is a tap to confirm the message on the screen, and you're done!

**Comment by nevets963** [comment]
Thanks for the insight. What does this mean for API access? Looks like N26 is now supporting Open Banking (must be enabled through the app) using token.io. Looks like we’ll need to use that in future.

**Comment by zNoobs** [comment]
From what I understand, token.io is not free, it is 250 GBP per month minimum.
So the (free) solution should be to use the same requests as the mobile app (use the same API) so we won't need the 2FA.

Edit: And for the actual API used in this git, it should be updated to let the user enter the 2FA SMS Code, or wait for the user to confirm on the app...

**Comment by nevets963** [comment]
Yes, this would be super cool! Anyway to collaborate to submit a PR? A free option sounds good to me :)

**Comment by zNoobs** [comment]
Someone did it before:
https://medium.com/@fabrizio2210/how-i-get-n26-api-and-automate-a-transfer-2ae630c8f7fe
But apparently there is this mfa error now too, maybe because he doesn't send requests as a paired device.

More info about the N26 update:
https://n26.com/en-eu/blog/what-is-psd2

**Comment by nevets963** [comment]
@zNoobs I just submitted the PR #7 - thoughts?
